# Generated by Django 6.0.2 on 2026-02-04 18:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_address_id_order_payment_method_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_holder_name', models.TextField()),
                ('card_number', models.TextField()),
                ('card_type', models.TextField()),
                ('expiry_month', models.TextField()),
                ('expiry_year', models.TextField()),
                ('cvv', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('razorpay_card_token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_ref', models.CharField(max_length=255)),
                ('webhook_data', models.JSONField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='received', max_length=50)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
            options={
                'db_table': 'payment_webhooks',
            },
        ),
    ]
