-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.admin_action_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  admin_id uuid NOT NULL,
  action text NOT NULL,
  resource_type text NOT NULL,
  resource_id uuid,
  details jsonb DEFAULT '{}'::jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  target_type text,
  target_id uuid,
  old_values jsonb,
  new_values jsonb,
  severity text DEFAULT 'info'::text CHECK (severity = ANY (ARRAY['info'::text, 'warning'::text, 'error'::text, 'critical'::text])),
  CONSTRAINT admin_action_logs_pkey PRIMARY KEY (id),
  CONSTRAINT admin_action_logs_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.admin_users(id)
);
CREATE TABLE public.admin_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  admin_id uuid,
  user_id uuid,
  session_token text NOT NULL UNIQUE,
  refresh_token text NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  is_active boolean DEFAULT true,
  device_info jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admin_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT admin_sessions_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.admin_users(id),
  CONSTRAINT admin_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.admin_users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email text NOT NULL UNIQUE,
  password_hash text,
  full_name text NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['super_admin'::text, 'admin'::text, 'moderator'::text])),
  permissions jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  profile_image_url text,
  CONSTRAINT admin_users_pkey PRIMARY KEY (id),
  CONSTRAINT admin_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.app_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  setting_key text NOT NULL UNIQUE,
  setting_value jsonb NOT NULL,
  description text,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT app_settings_pkey PRIMARY KEY (id),
  CONSTRAINT app_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.cart_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  cart_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  selected_size text NOT NULL,
  selected_color text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cart_items_pkey PRIMARY KEY (id),
  CONSTRAINT cart_items_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES public.carts(id),
  CONSTRAINT cart_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.carts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT carts_pkey PRIMARY KEY (id),
  CONSTRAINT carts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  description text,
  image_url text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  requires_size_chart boolean DEFAULT false,
  default_size_chart_template_id uuid,
  size_chart_applicability text DEFAULT 'never'::text CHECK (size_chart_applicability = ANY (ARRAY['always'::text, 'conditional'::text, 'never'::text])),
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT categories_default_size_chart_template_id_fkey FOREIGN KEY (default_size_chart_template_id) REFERENCES public.size_chart_templates(id)
);
CREATE TABLE public.chat_analytics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid,
  user_id uuid,
  action_type text NOT NULL,
  action_data jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT chat_analytics_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.chat_conversations(id),
  CONSTRAINT chat_analytics_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.chat_conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  title text DEFAULT 'New Conversation'::text,
  last_message_at timestamp with time zone DEFAULT now(),
  is_resolved boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT chat_conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.chat_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid,
  sender_type text NOT NULL CHECK (sender_type = ANY (ARRAY['user'::text, 'bot'::text, 'agent'::text])),
  message_text text NOT NULL,
  message_type text DEFAULT 'text'::text CHECK (message_type = ANY (ARRAY['text'::text, 'product'::text, 'image'::text, 'file'::text, 'quick_reply'::text])),
  metadata jsonb,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.chat_conversations(id)
);
CREATE TABLE public.contact_branches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  branch_name text NOT NULL,
  mall_name text,
  address_line_1 text NOT NULL,
  address_line_2 text,
  city text NOT NULL,
  state text NOT NULL,
  country text NOT NULL,
  phone text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contact_branches_pkey PRIMARY KEY (id)
);
CREATE TABLE public.contact_info (
  id uuid NOT NULL DEFAULT gen_random_uuid() CHECK (id = '00000000-0000-0000-0000-000000000000'::uuid),
  contact jsonb NOT NULL DEFAULT '{"email": "", "phone": "", "whatsapp": ""}'::jsonb,
  office jsonb NOT NULL DEFAULT '{"name": "", "phone": "", "location": {"city": "", "state": "", "country": "", "address_line_1": "", "address_line_2": ""}}'::jsonb,
  customer_service_promise jsonb NOT NULL DEFAULT '{"email": "", "phone": "", "policy": "", "whatsapp": ""}'::jsonb,
  social_media jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contact_info_pkey PRIMARY KEY (id)
);
CREATE TABLE public.conversation_context (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  conversation_id uuid,
  user_id uuid,
  user_message text NOT NULL,
  intent_type text NOT NULL,
  intent_confidence numeric DEFAULT 0.0,
  ai_response text NOT NULL,
  extracted_info text DEFAULT ''::text,
  products_mentioned ARRAY DEFAULT '{}'::uuid[],
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT conversation_context_pkey PRIMARY KEY (id),
  CONSTRAINT conversation_context_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT conversation_context_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.chat_conversations(id)
);
CREATE TABLE public.currency_rates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  from_currency text NOT NULL,
  to_currency text NOT NULL,
  rate numeric NOT NULL,
  source text DEFAULT 'manual'::text,
  updated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT currency_rates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.delivery_info (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL UNIQUE,
  return_window_days integer DEFAULT 7,
  cod_eligible boolean DEFAULT true,
  free_delivery boolean DEFAULT false,
  shipping_fee numeric DEFAULT 0,
  eta_min_days integer DEFAULT 3,
  eta_max_days integer DEFAULT 7,
  delivery_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT delivery_info_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_info_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.dynamic_size_chart_fields (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  size_chart_id uuid NOT NULL,
  field_name character varying NOT NULL,
  field_type character varying NOT NULL CHECK (field_type::text = ANY (ARRAY['measurement'::character varying, 'text'::character varying, 'number'::character varying, 'dropdown'::character varying, 'boolean'::character varying, 'range'::character varying]::text[])),
  field_unit character varying,
  is_required boolean DEFAULT false,
  field_options jsonb,
  placeholder_text text,
  help_text text,
  sort_order integer DEFAULT 0,
  validation_rules jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dynamic_size_chart_fields_pkey PRIMARY KEY (id),
  CONSTRAINT dynamic_size_chart_fields_size_chart_id_fkey FOREIGN KEY (size_chart_id) REFERENCES public.vendor_size_chart_templates(id)
);
CREATE TABLE public.escrow_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  vendor_id uuid,
  amount numeric NOT NULL,
  status character varying DEFAULT 'held'::character varying,
  release_date timestamp without time zone,
  payout_id uuid,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT escrow_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT escrow_transactions_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT escrow_transactions_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT escrow_transactions_payout_id_fkey FOREIGN KEY (payout_id) REFERENCES public.vendor_payouts(id)
);
CREATE TABLE public.faqs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  question text NOT NULL,
  answer text NOT NULL,
  category text NOT NULL,
  order_index integer NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT faqs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.feature_posters (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  title text NOT NULL,
  subtitle text NOT NULL,
  media_url text NOT NULL,
  aspect_ratio text DEFAULT '16:9'::text,
  cta_label text,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT feature_posters_pkey PRIMARY KEY (id),
  CONSTRAINT feature_posters_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.hero_section (
  id uuid NOT NULL DEFAULT gen_random_uuid() CHECK (id = '00000000-0000-0000-0000-000000000001'::uuid),
  trusted_by_text text DEFAULT 'Trusted by 100,000+ customers'::text,
  headline text NOT NULL DEFAULT 'Discover Amazing Products at Great Prices'::text,
  headline_highlight text DEFAULT 'Products'::text,
  description text DEFAULT 'Shop the latest trends with fast delivery, secure payments, and exceptional customer service. Your perfect shopping experience starts here.'::text,
  media_type text DEFAULT 'image'::text CHECK (media_type = ANY (ARRAY['image'::text, 'video'::text])),
  media_url text,
  primary_button jsonb NOT NULL DEFAULT '{"link": "/products", "text": "Shop Now", "style": "primary"}'::jsonb,
  secondary_button jsonb NOT NULL DEFAULT '{"link": "/categories", "text": "Browse Categories", "style": "secondary"}'::jsonb,
  features jsonb NOT NULL DEFAULT '[{"icon": "delivery", "text": "Free Shipping On orders over ₦50.00"}, {"icon": "shield", "text": "Secure Payment 100% protected"}, {"icon": "return", "text": "Easy Returns 30-day policy"}]'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  image_url text,
  video_url text,
  CONSTRAINT hero_section_pkey PRIMARY KEY (id)
);
CREATE TABLE public.loyalty_badges (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  description text,
  icon_url text,
  badge_type text NOT NULL CHECK (badge_type = ANY (ARRAY['order_count'::text, 'spending_amount'::text, 'streak'::text, 'special'::text])),
  requirement_value integer,
  bonus_points integer DEFAULT 0,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT loyalty_badges_pkey PRIMARY KEY (id)
);
CREATE TABLE public.loyalty_earning_rules (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  rule_name text NOT NULL,
  rule_type text DEFAULT 'order_purchase'::text CHECK (rule_type = ANY (ARRAY['order_purchase'::text, 'milestone'::text, 'bonus'::text])),
  points_per_currency_unit numeric DEFAULT 1.0,
  minimum_order_amount numeric DEFAULT 0,
  multiplier numeric DEFAULT 1.0,
  is_active boolean DEFAULT true,
  valid_from timestamp with time zone,
  valid_until timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT loyalty_earning_rules_pkey PRIMARY KEY (id)
);
CREATE TABLE public.loyalty_points (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  points_balance integer DEFAULT 0,
  lifetime_points integer DEFAULT 0,
  tier text DEFAULT 'bronze'::text CHECK (tier = ANY (ARRAY['bronze'::text, 'silver'::text, 'gold'::text, 'platinum'::text])),
  tier_updated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT loyalty_points_pkey PRIMARY KEY (id),
  CONSTRAINT loyalty_points_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.loyalty_rewards (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  description text,
  points_required integer NOT NULL,
  reward_type text NOT NULL CHECK (reward_type = ANY (ARRAY['discount_percentage'::text, 'discount_fixed'::text, 'free_shipping'::text])),
  discount_percentage numeric,
  discount_amount numeric,
  minimum_order_amount numeric DEFAULT 0,
  validity_days integer DEFAULT 30,
  max_redemptions_per_user integer,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT loyalty_rewards_pkey PRIMARY KEY (id)
);
CREATE TABLE public.loyalty_transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  points_change integer NOT NULL,
  transaction_type text NOT NULL CHECK (transaction_type = ANY (ARRAY['earn'::text, 'redeem'::text, 'expire'::text, 'adjustment'::text, 'bonus'::text])),
  reference_type text CHECK (reference_type = ANY (ARRAY['order'::text, 'voucher'::text, 'admin'::text, 'milestone'::text])),
  reference_id uuid,
  description text NOT NULL,
  points_balance_after integer NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT loyalty_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT loyalty_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.loyalty_vouchers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  reward_id uuid NOT NULL,
  voucher_code text NOT NULL UNIQUE,
  points_spent integer NOT NULL,
  discount_type text NOT NULL,
  discount_value numeric NOT NULL,
  minimum_order_amount numeric DEFAULT 0,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'used'::text, 'expired'::text])),
  redeemed_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  used_at timestamp with time zone,
  order_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT loyalty_vouchers_pkey PRIMARY KEY (id),
  CONSTRAINT loyalty_vouchers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT loyalty_vouchers_reward_id_fkey FOREIGN KEY (reward_id) REFERENCES public.loyalty_rewards(id),
  CONSTRAINT loyalty_vouchers_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer NOT NULL,
  price numeric NOT NULL,
  selected_size text NOT NULL,
  selected_color text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.order_status_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid NOT NULL,
  previous_status text,
  new_status text NOT NULL,
  changed_by uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT order_status_history_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_status_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.admin_users(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  address_id uuid,
  payment_method_id uuid,
  subtotal numeric NOT NULL,
  shipping_fee numeric NOT NULL,
  total numeric NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'processing'::text, 'shipped'::text, 'delivered'::text, 'cancelled'::text, 'refunded'::text, 'returned'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  order_number text,
  vendor_id uuid,
  shipping_method text,
  tracking_number text,
  estimated_delivery timestamp with time zone,
  discount_amount numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  notes text,
  updated_at timestamp with time zone DEFAULT now(),
  squad_transaction_ref character varying,
  squad_gateway_ref character varying,
  payment_status character varying DEFAULT 'pending'::character varying,
  escrow_status character varying DEFAULT 'none'::character varying,
  escrow_release_date timestamp with time zone,
  vendor_payout_amount numeric,
  loyalty_points_earned integer DEFAULT 0,
  loyalty_voucher_code text,
  loyalty_discount_applied numeric DEFAULT 0,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_address_id_fkey FOREIGN KEY (address_id) REFERENCES public.shipping_addresses(id),
  CONSTRAINT orders_payment_method_id_fkey FOREIGN KEY (payment_method_id) REFERENCES public.payment_methods(id),
  CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT orders_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id)
);
CREATE TABLE public.other_payment_methods (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_id uuid NOT NULL,
  payment_method text NOT NULL,
  details jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT other_payment_methods_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payment_methods (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  card_holder_name text NOT NULL,
  card_number text NOT NULL,
  card_type text NOT NULL,
  expiry_month text NOT NULL,
  expiry_year text NOT NULL,
  is_default boolean DEFAULT false,
  razorpay_card_token text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  cvv numeric,
  CONSTRAINT payment_methods_pkey PRIMARY KEY (id),
  CONSTRAINT payment_methods_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.payment_webhooks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  transaction_ref character varying NOT NULL,
  order_id uuid,
  webhook_data jsonb NOT NULL,
  status character varying NOT NULL,
  processed_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_webhooks_pkey PRIMARY KEY (id),
  CONSTRAINT payment_webhooks_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  user_email text NOT NULL,
  amount integer NOT NULL,
  currency text NOT NULL DEFAULT 'NGN'::text,
  transaction_ref text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'success'::text, 'failed'::text])),
  payment_type text NOT NULL DEFAULT 'one-time'::text CHECK (payment_type = ANY (ARRAY['one-time'::text, 'recurring'::text])),
  token text,
  gateway_response text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.payout_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payout_id uuid,
  transaction_type character varying NOT NULL,
  amount numeric NOT NULL,
  description text,
  reference_id character varying,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT payout_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT payout_transactions_payout_id_fkey FOREIGN KEY (payout_id) REFERENCES public.vendor_payouts(id)
);
CREATE TABLE public.platform_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  category text NOT NULL,
  key text NOT NULL,
  value jsonb NOT NULL,
  description text,
  is_public boolean DEFAULT false,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT platform_settings_pkey PRIMARY KEY (id),
  CONSTRAINT platform_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.admin_users(id)
);
CREATE TABLE public.product_approval_queue (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  vendor_id uuid NOT NULL,
  action_type text NOT NULL CHECK (action_type = ANY (ARRAY['create'::text, 'update'::text, 'delete'::text])),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  submitted_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  admin_notes text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  priority text DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_approval_queue_pkey PRIMARY KEY (id),
  CONSTRAINT product_approval_queue_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT product_approval_queue_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT product_approval_queue_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.admin_users(id)
);
CREATE TABLE public.product_highlights (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  label text NOT NULL,
  icon_url text,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_highlights_pkey PRIMARY KEY (id),
  CONSTRAINT product_highlights_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.product_offers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['coupon'::text, 'bank'::text, 'delivery'::text, 'cod'::text, 'timer'::text])),
  code text,
  description text NOT NULL,
  expiry_date timestamp with time zone,
  icon_url text,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_offers_pkey PRIMARY KEY (id),
  CONSTRAINT product_offers_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.product_qa (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  user_id uuid,
  question text NOT NULL,
  answer text,
  answered_by uuid,
  answered_at timestamp with time zone,
  is_helpful_count integer DEFAULT 0,
  is_verified boolean DEFAULT false,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'answered'::text, 'hidden'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  vendor_response text,
  vendor_response_date timestamp with time zone,
  vendor_id uuid,
  CONSTRAINT product_qa_pkey PRIMARY KEY (id),
  CONSTRAINT product_qa_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT product_qa_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT product_qa_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT product_qa_answered_by_fkey FOREIGN KEY (answered_by) REFERENCES auth.users(id)
);
CREATE TABLE public.product_recommendations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL UNIQUE,
  similar_products ARRAY DEFAULT '{}'::uuid[],
  from_seller_products ARRAY DEFAULT '{}'::uuid[],
  you_might_also_like ARRAY DEFAULT '{}'::uuid[],
  algorithm_version text DEFAULT 'v1.0'::text,
  confidence_score numeric DEFAULT 0.5,
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT product_recommendations_pkey PRIMARY KEY (id),
  CONSTRAINT product_recommendations_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.product_reviews (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  user_id uuid,
  order_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title text,
  content text NOT NULL,
  images ARRAY DEFAULT '{}'::text[],
  verified_purchase boolean DEFAULT false,
  helpful_count integer DEFAULT 0,
  reported_count integer DEFAULT 0,
  status text DEFAULT 'published'::text CHECK (status = ANY (ARRAY['published'::text, 'hidden'::text, 'pending_moderation'::text])),
  vendor_response text,
  vendor_response_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT product_reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT product_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT product_reviews_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.product_reviews_summary (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL UNIQUE,
  with_media integer DEFAULT 0,
  histogram ARRAY DEFAULT ARRAY[0, 0, 0, 0, 0],
  total_reviews integer DEFAULT 0,
  average_rating numeric DEFAULT 0,
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT product_reviews_summary_pkey PRIMARY KEY (id),
  CONSTRAINT product_reviews_summary_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.product_size_chart_assignments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  template_id uuid,
  vendor_template_id uuid,
  custom_data jsonb,
  assignment_type character varying NOT NULL CHECK (assignment_type::text = ANY (ARRAY['admin_template'::character varying, 'vendor_template'::character varying, 'custom'::character varying]::text[])),
  assigned_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_size_chart_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT product_size_chart_assignments_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT product_size_chart_assignments_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.size_chart_templates(id),
  CONSTRAINT product_size_chart_assignments_vendor_template_id_fkey FOREIGN KEY (vendor_template_id) REFERENCES public.vendor_size_chart_templates(id),
  CONSTRAINT product_size_chart_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.vendors(id)
);
CREATE TABLE public.product_specifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  group_name text NOT NULL,
  spec_name text NOT NULL,
  spec_value text NOT NULL,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_specifications_pkey PRIMARY KEY (id),
  CONSTRAINT product_specifications_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  description text,
  price numeric NOT NULL,
  images text NOT NULL DEFAULT 'https://mfbnxhjfbzbxvuzzbryu.supabase.co/storage/v1/object/sign/categories/6f81a0ef-a66a-47a8-ad4a-5c248da0cdb4.JPG?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJjYXRlZ29yaWVzLzZmODFhMGVmLWE2NmEtNDdhOC1hZDRhLTVjMjQ4ZGEwY2RiNC5KUEciLCJpYXQiOjE3MzY1NzgwOTEsImV4cCI6MTc2ODExNDA5MX0.7IU1gNlpGu1I0U_BAa0zJt-7I67uvJ3snKJ1_f_L1Mk&t=2025-01-11T06%3A48%3A11.904Z'::text,
  sizes ARRAY NOT NULL,
  rating numeric NOT NULL DEFAULT 0,
  reviews integer NOT NULL DEFAULT 0,
  in_stock boolean NOT NULL DEFAULT true,
  category_id uuid,
  brand text,
  discount_percentage numeric,
  is_on_sale boolean DEFAULT false,
  sale_price numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_featured boolean DEFAULT false,
  is_new_arrival boolean DEFAULT false,
  added_date timestamp with time zone DEFAULT now(),
  search_vector tsvector DEFAULT to_tsvector('english'::regconfig, ((((name || ' '::text) || description) || ' '::text) || brand)),
  vendor_id uuid,
  approval_status text DEFAULT 'approved'::text CHECK (approval_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'under_review'::text])),
  sku text UNIQUE,
  stock_quantity integer DEFAULT 0,
  weight numeric,
  dimensions jsonb,
  shipping_required boolean DEFAULT true,
  meta_title text,
  meta_description text,
  tags ARRAY,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'draft'::text, 'archived'::text])),
  color_images jsonb CHECK (color_images IS NULL OR jsonb_typeof(color_images) = 'object'::text),
  size_chart_template_id uuid,
  custom_size_chart_data jsonb,
  size_guide_type text DEFAULT 'template'::text CHECK (size_guide_type = ANY (ARRAY['template'::text, 'custom'::text, 'none'::text])),
  embedding USER-DEFINED,
  subtitle text,
  mrp numeric,
  currency text DEFAULT 'INR'::text,
  orders_count integer DEFAULT 0,
  box_contents ARRAY,
  usage_instructions ARRAY,
  care_instructions ARRAY,
  safety_notes ARRAY,
  seo_data jsonb,
  video_url text,
  base_currency text DEFAULT 'USD'::text,
  converted_prices jsonb DEFAULT '{}'::jsonb,
  product_type text,
  sizing_required boolean DEFAULT false,
  size_chart_override text DEFAULT 'auto'::text CHECK (size_chart_override = ANY (ARRAY['show'::text, 'hide'::text, 'auto'::text])),
  subcategory_id uuid,
  colors jsonb NOT NULL,
  rejection_reason text,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id),
  CONSTRAINT products_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT products_size_chart_template_id_fkey FOREIGN KEY (size_chart_template_id) REFERENCES public.size_chart_templates(id),
  CONSTRAINT products_subcategory_id_fkey FOREIGN KEY (subcategory_id) REFERENCES public.subcategories(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  full_name text,
  phone_number text,
  image_path text,
  updated_at timestamp with time zone DEFAULT now(),
  role USER-DEFINED NOT NULL DEFAULT 'customer'::user_role,
  is_deleted boolean DEFAULT false,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.promotional_banners (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text,
  description text,
  subtitle text,
  discount_value numeric,
  discount_type text CHECK (discount_type = ANY (ARRAY['percentage'::text, 'fixed'::text, 'none'::text])),
  coupon_code text,
  background_image_url text,
  show_title boolean DEFAULT true,
  show_description boolean DEFAULT true,
  show_subtitle boolean DEFAULT false,
  show_discount boolean DEFAULT true,
  show_coupon_code boolean DEFAULT true,
  show_background_image boolean DEFAULT false,
  title_color text DEFAULT '#000000'::text,
  description_color text DEFAULT '#666666'::text,
  subtitle_color text DEFAULT '#888888'::text,
  discount_color text DEFAULT '#FF0000'::text,
  coupon_code_color text DEFAULT '#0000FF'::text,
  background_color text DEFAULT '#FFFFFF'::text,
  overlay_color text DEFAULT 'rgba(0,0,0,0.3)'::text,
  text_alignment text DEFAULT 'center'::text CHECK (text_alignment = ANY (ARRAY['left'::text, 'center'::text, 'right'::text])),
  banner_height text DEFAULT '300px'::text,
  padding text DEFAULT '20px'::text,
  border_radius text DEFAULT '8px'::text,
  is_active boolean DEFAULT true,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  priority integer DEFAULT 0,
  is_template boolean DEFAULT false,
  template_name text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  custom_styles jsonb DEFAULT '{}'::jsonb,
  button_text text,
  button_url text,
  button_color text DEFAULT '#007BFF'::text,
  button_text_color text DEFAULT '#FFFFFF'::text,
  show_button boolean DEFAULT false,
  banner_size text DEFAULT 'medium'::text CHECK (banner_size = ANY (ARRAY['small'::text, 'medium'::text, 'large'::text])),
  CONSTRAINT promotional_banners_pkey PRIMARY KEY (id),
  CONSTRAINT promotional_banners_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.admin_users(id)
);
CREATE TABLE public.review_helpfulness (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  review_id uuid NOT NULL,
  user_id uuid NOT NULL,
  is_helpful boolean NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT review_helpfulness_pkey PRIMARY KEY (id),
  CONSTRAINT review_helpfulness_review_id_fkey FOREIGN KEY (review_id) REFERENCES public.product_reviews(id),
  CONSTRAINT review_helpfulness_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.search_analytics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  query text NOT NULL,
  result_count integer NOT NULL,
  filters jsonb,
  timestamp timestamp with time zone DEFAULT now(),
  CONSTRAINT search_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT search_analytics_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.shipping_addresses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  phone text NOT NULL,
  address_line1 text NOT NULL,
  address_line2 text,
  city text NOT NULL,
  state text NOT NULL,
  zip text NOT NULL,
  country text,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  type text,
  CONSTRAINT shipping_addresses_pkey PRIMARY KEY (id),
  CONSTRAINT shipping_addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.size_chart_analytics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  template_id uuid,
  vendor_template_id uuid,
  user_id uuid,
  action_type character varying NOT NULL,
  selected_size character varying,
  session_id character varying,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT size_chart_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT size_chart_analytics_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT size_chart_analytics_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.size_chart_templates(id),
  CONSTRAINT size_chart_analytics_vendor_template_id_fkey FOREIGN KEY (vendor_template_id) REFERENCES public.vendor_size_chart_templates(id),
  CONSTRAINT size_chart_analytics_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.size_chart_entries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  template_id uuid,
  size_name text NOT NULL,
  measurements jsonb NOT NULL,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT size_chart_entries_pkey PRIMARY KEY (id),
  CONSTRAINT size_chart_entries_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.size_chart_templates(id)
);
CREATE TABLE public.size_chart_migration_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  size_chart_id uuid NOT NULL,
  old_measurement_types jsonb,
  migration_status character varying DEFAULT 'pending'::character varying CHECK (migration_status::text = ANY (ARRAY['pending'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])),
  migration_notes text,
  migrated_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT size_chart_migration_log_pkey PRIMARY KEY (id),
  CONSTRAINT size_chart_migration_log_size_chart_id_fkey FOREIGN KEY (size_chart_id) REFERENCES public.vendor_size_chart_templates(id)
);
CREATE TABLE public.size_chart_templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  category_id uuid,
  subcategory text,
  measurement_types jsonb NOT NULL,
  measurement_instructions text,
  size_recommendations jsonb,
  chart_type text DEFAULT 'standard'::text CHECK (chart_type = ANY (ARRAY['standard'::text, 'footwear'::text, 'accessories'::text, 'custom'::text])),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT size_chart_templates_pkey PRIMARY KEY (id),
  CONSTRAINT size_chart_templates_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.subcategories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  description text,
  category_id uuid NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subcategories_pkey PRIMARY KEY (id),
  CONSTRAINT fk_subcategories_category_id FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.subscription_plans (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  description text,
  price numeric NOT NULL,
  billing_cycle text NOT NULL CHECK (billing_cycle = ANY (ARRAY['monthly'::text, 'yearly'::text])),
  features jsonb DEFAULT '{}'::jsonb,
  limits jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.support_info (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title text NOT NULL,
  subtitle text,
  type text NOT NULL,
  icon text NOT NULL,
  action_type text,
  action_value text,
  availability text,
  order_index integer NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT support_info_pkey PRIMARY KEY (id)
);
CREATE TABLE public.support_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ticket_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  sender_role text NOT NULL CHECK (sender_role = ANY (ARRAY['vendor'::text, 'admin'::text])),
  message_content text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT support_messages_pkey PRIMARY KEY (id),
  CONSTRAINT support_messages_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.support_tickets(id),
  CONSTRAINT support_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES auth.users(id)
);
CREATE TABLE public.support_tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vendor_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'closed'::text, 'in_progress'::text])),
  subject text NOT NULL,
  last_updated timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  priority text DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])),
  assigned_to uuid,
  category text DEFAULT 'general'::text,
  resolved_at timestamp with time zone,
  resolved_by uuid,
  CONSTRAINT support_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT support_tickets_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT support_tickets_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.admin_users(id),
  CONSTRAINT support_tickets_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.admin_users(id)
);
CREATE TABLE public.user_badges (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  badge_id uuid NOT NULL,
  earned_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_badges_pkey PRIMARY KEY (id),
  CONSTRAINT user_badges_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_badges_badge_id_fkey FOREIGN KEY (badge_id) REFERENCES public.loyalty_badges(id)
);
CREATE TABLE public.user_currency_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  preferred_currency text NOT NULL DEFAULT 'USD'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_currency_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT user_currency_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.vendor_applications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  vendor_id uuid,
  application_type text NOT NULL CHECK (application_type = ANY (ARRAY['new_vendor'::text, 'reactivation'::text, 'upgrade'::text])),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'under_review'::text, 'approved'::text, 'rejected'::text])),
  submitted_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  admin_notes text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT vendor_applications_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_applications_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT vendor_applications_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.admin_users(id)
);
CREATE TABLE public.vendor_bank_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vendor_id uuid,
  bank_code character varying NOT NULL,
  account_number character varying NOT NULL,
  account_name character varying NOT NULL,
  is_verified boolean DEFAULT false,
  is_default boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  bank_name character varying,
  status character varying DEFAULT 'pending_approval'::character varying,
  admin_notes text,
  reviewed_at timestamp with time zone,
  CONSTRAINT vendor_bank_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_bank_accounts_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id)
);
CREATE TABLE public.vendor_follows (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  vendor_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT vendor_follows_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_follows_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT vendor_follows_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id)
);
CREATE TABLE public.vendor_payouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vendor_id uuid,
  amount numeric NOT NULL,
  currency character varying DEFAULT 'NGN'::character varying,
  status character varying DEFAULT 'pending'::character varying,
  squad_transaction_ref character varying,
  bank_account_id uuid,
  requested_at timestamp without time zone DEFAULT now(),
  processed_at timestamp without time zone,
  completed_at timestamp without time zone,
  admin_notes text,
  failure_reason text,
  CONSTRAINT vendor_payouts_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_payouts_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT vendor_payouts_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.vendor_bank_accounts(id)
);
CREATE TABLE public.vendor_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vendor_id uuid NOT NULL,
  user_id uuid NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  review_text text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT vendor_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_reviews_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT vendor_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.vendor_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vendor_id uuid NOT NULL,
  user_id uuid NOT NULL,
  session_token text NOT NULL UNIQUE,
  refresh_token text,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  device_info jsonb,
  ip_address inet,
  CONSTRAINT vendor_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_sessions_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT vendor_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.vendor_size_chart_templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  vendor_id uuid NOT NULL,
  name character varying NOT NULL,
  category_id uuid,
  subcategory character varying,
  measurement_types jsonb NOT NULL,
  measurement_instructions text,
  size_recommendations jsonb,
  chart_type character varying DEFAULT 'custom'::character varying,
  template_data jsonb NOT NULL,
  approval_status character varying DEFAULT 'pending'::character varying CHECK (approval_status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[])),
  approved_by uuid,
  approved_at timestamp with time zone,
  rejection_reason text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_dynamic boolean DEFAULT false,
  schema_version character varying DEFAULT '1.0'::character varying,
  migration_completed_at timestamp with time zone,
  image_url text,
  CONSTRAINT vendor_size_chart_templates_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_size_chart_templates_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT vendor_size_chart_templates_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id),
  CONSTRAINT vendor_size_chart_templates_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.vendor_subscriptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  vendor_id uuid NOT NULL,
  subscription_plan_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'cancelled'::text, 'expired'::text, 'suspended'::text])),
  started_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  auto_renew boolean DEFAULT true,
  payment_method_id uuid,
  last_payment_date timestamp with time zone,
  next_payment_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT vendor_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_subscriptions_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT vendor_subscriptions_subscription_plan_id_fkey FOREIGN KEY (subscription_plan_id) REFERENCES public.subscription_plans(id)
);
CREATE TABLE public.vendors (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  business_name text NOT NULL,
  business_description text,
  business_logo text,
  business_email text NOT NULL,
  business_phone text,
  business_address text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'suspended'::text, 'inactive'::text])),
  is_featured boolean DEFAULT false,
  average_rating numeric DEFAULT 0 CHECK (average_rating >= 0::numeric AND average_rating <= 5::numeric),
  total_reviews integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  business_registration_number text,
  tax_id text,
  business_type text CHECK (business_type = ANY (ARRAY['individual'::text, 'company'::text, 'partnership'::text, 'llc'::text])),
  verification_status text DEFAULT 'unverified'::text CHECK (verification_status = ANY (ARRAY['unverified'::text, 'pending'::text, 'verified'::text, 'rejected'::text])),
  verification_documents jsonb,
  total_sales numeric DEFAULT 0,
  total_orders integer DEFAULT 0,
  commission_rate numeric DEFAULT 10.00,
  payout_schedule text DEFAULT 'monthly'::text CHECK (payout_schedule = ANY (ARRAY['weekly'::text, 'bi-weekly'::text, 'monthly'::text])),
  bank_account_info jsonb,
  payment_method_preference text DEFAULT 'bank_transfer'::text,
  last_login_at timestamp with time zone,
  is_active boolean DEFAULT true,
  admin_notes text,
  total_earnings numeric DEFAULT 0,
  pending_payouts numeric DEFAULT 0,
  total_paid_out numeric DEFAULT 0,
  available_balance numeric DEFAULT 0,
  rejection_reason text,
  CONSTRAINT vendors_pkey PRIMARY KEY (id),
  CONSTRAINT vendors_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.warranty_info (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL UNIQUE,
  type text NOT NULL,
  duration text NOT NULL,
  description text,
  terms_url text,
  coverage_details ARRAY,
  exclusions ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT warranty_info_pkey PRIMARY KEY (id),
  CONSTRAINT warranty_info_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.wishlist (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  product_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT wishlist_pkey PRIMARY KEY (id),
  CONSTRAINT wishlist_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT wishlist_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);