# Generated by Django 6.0.2 on 2026-02-05 12:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_escrow_release_date_order_escrow_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_url', models.TextField(blank=True, null=True)),
                ('badge_type', models.CharField(choices=[('order_count', 'Order Count'), ('spending_amount', 'Spending Amount'), ('streak', 'Streak'), ('special', 'Special')], max_length=50)),
                ('requirement_value', models.IntegerField(blank=True, null=True)),
                ('bonus_points', models.IntegerField(default=0)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'loyalty_badges',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyEarningRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.TextField()),
                ('rule_type', models.CharField(choices=[('order_purchase', 'Order Purchase'), ('milestone', 'Milestone'), ('bonus', 'Bonus')], default='order_purchase', max_length=50)),
                ('points_per_currency_unit', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loyalty_earning_rules',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('points_required', models.IntegerField()),
                ('reward_type', models.CharField(choices=[('discount_percentage', 'Discount Percentage'), ('discount_fixed', 'Discount Fixed'), ('free_shipping', 'Free Shipping')], max_length=50)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('validity_days', models.IntegerField(default=30)),
                ('max_redemptions_per_user', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loyalty_rewards',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyPoints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_balance', models.IntegerField(default=0)),
                ('lifetime_points', models.IntegerField(default=0)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20)),
                ('tier_updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loyalty_points',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_change', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('earn', 'Earn'), ('redeem', 'Redeem'), ('expire', 'Expire'), ('adjustment', 'Adjustment'), ('bonus', 'Bonus')], max_length=20)),
                ('reference_type', models.CharField(blank=True, choices=[('order', 'Order'), ('voucher', 'Voucher'), ('admin', 'Admin'), ('milestone', 'Milestone')], max_length=20, null=True)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField()),
                ('points_balance_after', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loyalty_transactions',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyVoucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voucher_code', models.TextField(unique=True)),
                ('points_spent', models.IntegerField()),
                ('discount_type', models.TextField()),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired')], default='active', max_length=20)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_voucher', to='orders.order')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyalty.loyaltyreward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loyalty_vouchers',
            },
        ),
    ]
