# Generated by Django 6.0.2 on 2026-02-05 12:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=255)),
                ('action_type', models.CharField(blank=True, max_length=50, null=True)),
                ('action_value', models.TextField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, max_length=100, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'support_info',
            },
        ),
        migrations.CreateModel(
            name='PromotionalBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField()),
                ('link_url', models.TextField(blank=True, null=True)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=50)),
                ('text_color', models.CharField(default='#000000', max_length=50)),
                ('position', models.CharField(default='top', max_length=50)),
                ('page_location', models.CharField(default='home', max_length=50)),
                ('padding', models.CharField(default='20px', max_length=50)),
                ('border_radius', models.CharField(default='8px', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('is_template', models.BooleanField(default=False)),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_styles', models.JSONField(default=dict)),
                ('button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button_url', models.TextField(blank=True, null=True)),
                ('button_color', models.CharField(default='#007BFF', max_length=50)),
                ('button_text_color', models.CharField(default='#FFFFFF', max_length=50)),
                ('show_button', models.BooleanField(default=False)),
                ('banner_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_api.adminuser')),
            ],
            options={
                'db_table': 'promotional_banners',
            },
        ),
    ]
