# Generated by Django 6.0.2 on 2026-02-15 06:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contact", models.JSONField(default=dict)),
                ("office", models.JSONField(default=dict)),
                ("customer_service_promise", models.JSONField(default=dict)),
                ("social_media", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "contact_info",
            },
        ),
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("trusted_by_text", models.TextField(blank=True, null=True)),
                ("headline", models.TextField()),
                ("headline_highlight", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("media_type", models.CharField(blank=True, max_length=50, null=True)),
                ("media_url", models.TextField(blank=True, null=True)),
                ("image_url", models.TextField(blank=True, null=True)),
                ("video_url", models.TextField(blank=True, null=True)),
                ("primary_button", models.JSONField(default=dict)),
                ("secondary_button", models.JSONField(default=dict)),
                ("features", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "hero_section",
            },
        ),
    ]
