# Generated by Django 6.0.2 on 2026-02-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_address_id_order_payment_method_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='escrow_release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='escrow_status',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_payout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
