# Generated by Django 6.0.2 on 2026-02-14 18:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_escrow_release_date_order_escrow_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("phone", models.TextField()),
                ("address_line1", models.TextField()),
                ("address_line2", models.TextField(blank=True, null=True)),
                ("city", models.TextField()),
                ("state", models.TextField()),
                ("zip", models.TextField()),
                ("country", models.TextField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("type", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "shipping_addresses",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
    ]
