# Generated by Django 6.0.2 on 2026-02-04 18:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('images', models.TextField(default='https://example.com/default.jpg')),
                ('sizes', models.JSONField(default=list)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('reviews', models.IntegerField(default=0)),
                ('in_stock', models.BooleanField(default=True)),
                ('category_id', models.UUIDField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_on_sale', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('vendor_id', models.UUIDField(blank=True, null=True)),
                ('approval_status', models.CharField(default='approved', max_length=20)),
                ('sku', models.TextField(blank=True, null=True, unique=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('colors', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-added_date'],
            },
        ),
    ]
